# Generated by Django 3.1 on 2021-05-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20200927_0112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
