# Generated by Django 3.1 on 2021-12-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_qrId', models.CharField(max_length=100)),
                ('book_location', models.FloatField()),
                ('customer_location', models.FloatField()),
                ('prev_node', models.FloatField()),
                ('next_node', models.FloatField()),
                ('server_command', models.CharField(max_length=20)),
                ('compass_value', models.FloatField()),
                ('book_found', models.BooleanField()),
                ('book_fetching', models.BooleanField()),
                ('play_time', models.FloatField()),
            ],
        ),
    ]
